src/Examples/Examples.Mvc/ViewModels/CustomerViewModel.cs
namespace Examples.Mvc.ViewModels
{
    public class CustomerViewModel
    {
        public string AccountNumber { get; set; }

        public int CustomerID { get; set; }

        public PersonViewModel Person { get; set; }

        public StoreViewModel Store { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/PersonViewModel.cs
namespace Examples.Mvc.ViewModels
{
    using System;
    using Examples.Data;
    public class PersonViewModel
    {
        public int BusinessEntityID { get; set; }

        public string PersonType { get; set; }

        public bool NameStyle { get; set; }

        public string Title { get; set; }

        public string FirstName { get; set; }

        public string MiddleName { get; set; }

        public string LastName { get; set; }

        public string Suffix { get; set; }

        public int EmailPromotion { get; set; }

        public string AdditionalContactInfo { get; set; }

        public string Demographics { get; set; }

        public Guid rowguid { get; set; }

        public DateTime ModifiedDate { get; set; }

        public virtual Employee Employee { get; set; }

        public virtual BusinessEntity BusinessEntity { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/ProductCategoryViewModel.cs
namespace Examples.Mvc.ViewModels
{
    public partial class ProductCategoryViewModel
    {
        public int ProductCategoryID { get; set; }

        public string Name { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/ProductModelViewModel.cs
namespace Examples.Mvc.ViewModels
{
    using System;
    public partial class ProductModelViewModel
    {
        public string Name { get; set; }

        public DateTime? ModifiedDate { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/ProductSubcategoryViewModel.cs
namespace Examples.Mvc.ViewModels
{
    public partial class ProductSubcategoryViewModel
    {
        public string Name { get; set; }

        public virtual ProductCategoryViewModel ProductCategory { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/ProductViewModel.cs
namespace Examples.Mvc.ViewModels
{
    using System;
    public partial class ProductViewModel
    {
        public string Name { get; set; }

        public string Color { get; set; }

        public short ReorderPoint { get; set; }

        public decimal ListPrice { get; set; }

        public int DaysToManufacture { get; set; }

        public DateTime SellStartDate { get; set; }

        public DateTime? DiscontinuedDate { get; set; }

        public virtual UnitMeasureViewModel UnitMeasure { get; set; }

        public virtual ProductModelViewModel ProductModel { get; set; }

        public virtual ProductSubcategoryViewModel ProductSubcategory { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/StoreViewModel.cs
namespace Examples.Mvc.ViewModels
{
    using System;
    using Examples.Data;
    public class StoreViewModel
    {
        public int BusinessEntityID { get; set; }

        public string Name { get; set; }

        public int? SalesPersonID { get; set; }

        public string Demographics { get; set; }

        public string rowguid { get; set; }

        public DateTime ModifiedDate { get; set; }

        public virtual BusinessEntity BusinessEntity { get; set; }
    }
}

src/Examples/Examples.Mvc/ViewModels/UnitMeasureViewModel.cs
namespace Examples.Mvc.ViewModels
{
    public partial class UnitMeasureViewModel
    {
        public string Name { get; set; }
    }
}

src/Examples/Examples.Mvc/Controllers/CustomersController.cs
namespace Examples.Mvc.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Examples.Data;
    using Examples.Mvc.ViewModels;
    using JQDT.Models;
    using JQDT.MVC;

    public class CustomersController : Controller
    {
        private AdventureWorks context;

        public CustomersController()
        {
            this.context = new Data.AdventureWorks();
        }

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        [CustomJQDataTable]
        public ActionResult GetCustomersData()
        {
            var data = this.context.Customers.Select(x => new CustomerViewModel
            {
                CustomerID = x.CustomerID,
                AccountNumber = x.AccountNumber,
                Person = new PersonViewModel
                {
                    FirstName = x.Person.FirstName,
                    LastName = x.Person.LastName,
                },
                Store = new StoreViewModel
                {
                    Name = x.Store.Name,
                }
            });

            return this.View(data);
        }
    }

    public class CustomJQDataTableAttribute : JQDataTableAttribute
    {
        public override void OnDataProcessed(ref object data, RequestInfoModel requestInfoModel)
        {
            var list = ((IQueryable<CustomerViewModel>)data).ToList();
            list.ForEach(x => x.Person.FirstName = $"FN {x.Person.FirstName}");
            data = list.AsQueryable();
        }

        public override void OnSearchDataProcessing(ref object data, RequestInfoModel requestInfoModel)
        {
            if (requestInfoModel.TableParameters.Search.Value.ToLower() == "even")
            {
                var queryable = data as IOrderedQueryable<CustomerViewModel>;
                data = queryable.Where(x => x.CustomerID % 2 == 0);
                requestInfoModel.TableParameters.Search.Value = "";
            }
        }
    }
}

src/Examples/Examples.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examples.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Examples/Examples.Mvc/Controllers/ProductsController.cs
namespace Examples.Mvc.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Examples.Data;
    using Examples.Mvc.ViewModels;
    using JQDT.MVC;

    public class ProductsController : Controller
    {
        private AdventureWorks context;

        public ProductsController()
        {
            this.context = new Data.AdventureWorks();
        }

        public ActionResult Index()
        {
            return View();
        }

        [JQDataTable]
        public ActionResult GetProductsData()
        {
            var data = this.context.Products.Select(x => new ProductViewModel
            {
                Name = x.Name,
                Color = x.Color,
                ListPrice = x.ListPrice,
                DaysToManufacture = x.DaysToManufacture,
                DiscontinuedDate = x.DiscontinuedDate,
                SellStartDate = x.SellStartDate,
                ReorderPoint = x.ReorderPoint,
                ProductModel = new ProductModelViewModel
                {
                    Name = x.ProductModel.Name,
                    ModifiedDate = x.ProductModel.ModifiedDate
                },
                ProductSubcategory = new ProductSubcategoryViewModel
                {
                    Name = x.ProductSubcategory.Name,
                    ProductCategory = new ProductCategoryViewModel
                    {
                        Name = x.ProductSubcategory.ProductCategory.Name
                    }
                },
                UnitMeasure = new UnitMeasureViewModel
                {
                    Name = x.UnitMeasure.Name
                }
            });

            return this.View(data);
        }
    }
}

src/Examples/Examples.Mvc/Controllers/VendorsController.cs
namespace Examples.Mvc.Controllers
{
    using System.Linq;
    using System.Web.Mvc;
    using Examples.Data;
    using JQDT.MVC;

    public class VendorsController : Controller
    {
        private readonly AdventureWorks context;

        public VendorsController()
        {
            this.context = new Examples.Data.AdventureWorks();
        }

        public ActionResult Index()
        {
            return this.View();
        }

        [JQDataTable]
        public ActionResult GetVendorsData()
        {
            var data = this.context.Vendors.Select(x => new
            {
                BusinessEntityID = x.BusinessEntityID,
                CreditRating = x.CreditRating,
                ActiveFlag = x.ActiveFlag,
                AccountNumber = x.AccountNumber,
                ModifiedDate = x.ModifiedDate
            });

            return this.View(data);
        }
    }
}

src/Examples/Examples.Mvc/Views/AdventureWorks/Vendors.cshtml
<div>
    Age: from <input type="number" id="minCreditRating" value="1" class="reload-table" />
    to <input type="number" id="maxCreditRating" value="3" class="reload-table" />
</div>

<div>
    Business Entity ID = <input type="number" id="businessEntityId" value="" class="reload-table" />
</div>

<div>
    Modified Date = <input type="date" id="modifiedDate" value="" class="reload-table" />
</div>

@*<div>Srarting Date: from <input type="date" id="minStartDate" value="" class="reload-table" /> to <input type="date" id="maxStartDate" value="" class="reload-table" /></div>
    <div>Street number: from <input type="number" id="minStreetNumber" value="" class="reload-table" /> to <input type="number" id="maxStreetNumber" value="" class="reload-table" /></div>*@

<table id="SearchResultTable" class="display" cellspacing="0" width="100">
    <thead>
        <tr>
            <th>BusinessEntityID</th>
            <th>CreditRating</th>
            <th>ActiveFlag</th>
            <th>AccountNumber</th>
            <th>ModifiedDate</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>BusinessEntityID</th>
            <th>CreditRating</th>
            <th>ActiveFlag</th>
            <th>AccountNumber</th>
            <th>ModifiedDate</th>
        </tr>
    </tfoot>
</table>

@section Scripts {
    <script>


        var table = $('#SearchResultTable').DataTable({
            "proccessing": true,
            "serverSide": true,
            "ajax": {
                url: "@Url.Action("GetVendorsData", "AdventureWorks")",
                type: 'POST',
                "data": function (d) {
                    d.custom = {
                        "filters": {
                            "CreditRating": { "gte": $('#minCreditRating').val(), "lte": $('#maxCreditRating').val() },
                            "BusinessEntityID": { "eq": $('#businessEntityId').val() },
                            "ModifiedDate": { "eq": $('#modifiedDate').val() },
                        }
                    }
                }
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
           "columns": [
               { "data": "BusinessEntityID", searchable: false },
               { "data": "CreditRating", searchable: false },
               { "data": "ActiveFlag", "searchable": false },
               { "data": "AccountNumber", searchable: true },
               { "data": "ModifiedDate", "searchable": false},
            ],
           "columnDefs": [
               {
                   "render": function (data, type, row) {
                       date = new Date(parseInt(row.ModifiedDate.replace("/Date(", "").replace(")/", ""), 10));

                       return date.toLocaleDateString();
                   },
                   "targets": 4
               }
           ]

        });

        $('.reload-table').on('change', function () {
            table.ajax.reload();
        });
    </script>
}

src/Examples/Examples.Mvc/Views/Customers/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Store Name</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Store Name</th>
        </tr>
    </tfoot>
</table>

@section Scripts {
    <script>
        $('tfoot th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

        var table = $('table').DataTable({
            "proccessing": true,
            "serverSide": true,
            "ajax": {
                url: "@Url.Action("GetCustomersData", "Customers")",
                type: 'POST'
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
           "columns": [
               { "data": "CustomerID" },
               { "data": "Person.FirstName" },
               { "data": "Person.LastName" },
               { "data": "Store.Name" },
            ]
        });

        table.columns().every(function () {
            var that = this;

            $('input', this.footer()).on('change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    </script>
}

src/Examples/Examples.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/Examples/Examples.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/Examples/Examples.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h2>Products</h2>
        <p>
            Example with a simple configuration.
        </p>
        <p><a class="btn btn-default" href="~/Products">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Customers</h2>
        <p>Example showing the ability to support nested objects.</p>
        <p><a class="btn btn-default" href="~/Customers">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Vendors</h2>
        <p>Example using custom filters.</p>
        <p><a class="btn btn-default" href="~/Vendors">Learn more &raquo;</a></p>
    </div>
</div>

src/Examples/Examples.Mvc/Views/Products/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="SearchResultTable" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Color</th>
            <th>ListPrice</th>
            <th>DaysToManufacture</th>
            <th>DiscontinuedDate</th>
            <th>SellStartDate</th>
            <th>ReorderPoint</th>
            <th>ProductModel.Name</th>
            <th>ProductModel.ModifiedDate</th>
            <th>ProductSubcategory.Name</th>
            <th>ProductSubcategory.ProductCategory.Name</th>
            <th>UnitMeasure.Name</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>Name</th>
            <th>Color</th>
            <th>ListPrice</th>
            <th>DaysToManufacture</th>
            <th>DiscontinuedDate</th>
            <th>SellStartDate</th>
            <th>ReorderPoint</th>
            <th>ProductModel.Name</th>
            <th>ProductModel.ModifiedDate</th>
            <th>ProductSubcategory.Name</th>
            <th>ProductSubcategory.ProductCategory.Name</th>
            <th>UnitMeasure.Name</th>
        </tr>
    </tfoot>
</table>

@section Scripts {
    <script>
        $('#SearchResultTable tfoot th').each(function () {
            var title = $(this).text();
            $(this).html('<input type="text" placeholder="Search ' + title + '" />');
        });

        var table = $('#SearchResultTable').DataTable({
            "proccessing": true,
            "serverSide": true,
            "ajax": {
                //url: "@Url.Action("GetProductsData", "Products")",
                url: "http://localhost:62677/api/products",
                type: 'POST'
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
           "columns": [
               { "data": "Name", "searchable": true },
               { "data": "Color", "searchable": true },
               { "data": "ListPrice", "searchable": false },
               { "data": "DaysToManufacture", "searchable": false },
               { "data": "DiscontinuedDate", "searchable": false },
               { "data": "SellStartDate", "searchable": false },
               { "data": "ReorderPoint", "searchable": false },
               { "data": "ProductModel.Name", "searchable": true },
               { "data": "ProductModel.ModifiedDate", "searchable": false },
               { "data": "ProductSubcategory.Name", "searchable": true },
               { "data": "ProductSubcategory.ProductCategory.Name", "searchable": true },
               { "data": "UnitMeasure.Name", "searchable": true },
            ],
            "columnDefs": [
                {
                    "render": function (data, type, row) {
                        date = new Date(parseInt(row.SellStartDate.replace("/Date(", "").replace(")/", ""), 10));

                        return date.toLocaleString();
                    },
                    "targets": 5
                },
            ]
        });

        table.columns().every(function () {
            var that = this;

            $('input', this.footer()).on('change', function () {
                if (that.search() !== this.value) {
                    that
                        .search(this.value)
                        .draw();
                }
            });
        });
    </script>
}

src/Examples/Examples.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Scripts/DataTables-1.10.16/css/jquery.dataTables.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vendors", "Index", "Vendors")</li>
                    <li>@Html.ActionLink("Customers", "Index", "Customers")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/DataTables-1.10.16/js/jquery.dataTables.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Examples/Examples.Mvc/Views/Vendors/Index.cshtml
<div>
    CreditRating: from <input type="number" id="minCreditRating" value="1" class="reload-table" />
    to <input type="number" id="maxCreditRating" value="3" class="reload-table" />
</div>

<div>
    Business Entity ID = <input type="number" id="businessEntityId" value="" class="reload-table" />
</div>

<div>
    Modified Date = <input type="date" id="modifiedDate" value="" class="reload-table" />
</div>

<div>
    Account Number = <input type="text" id="accountNumber" value="" class="reload-table" />
</div>

<table id="SearchResultTable" class="display" cellspacing="0" width="100">
    <thead>
        <tr>
            <th>BusinessEntityID</th>
            <th>CreditRating</th>
            <th>ActiveFlag</th>
            <th>AccountNumber</th>
            <th>ModifiedDate</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>BusinessEntityID</th>
            <th>CreditRating</th>
            <th>ActiveFlag</th>
            <th>AccountNumber</th>
            <th>ModifiedDate</th>
        </tr>
    </tfoot>
</table>

@section Scripts {
    <script>


        var table = $('#SearchResultTable').DataTable({
            "proccessing": true,
            "serverSide": true,
            "ajax": {
                url: "@Url.Action("GetVendorsData", "Vendors")",
                type: 'POST',
                "data": function (d) {
                    d.custom = {
                        "filters": {
                            "CreditRating": { "gte": $('#minCreditRating').val(), "lte": $('#maxCreditRating').val() },
                            "BusinessEntityID": { "eq": $('#businessEntityId').val() },
                            "ModifiedDate": { "eq": $('#modifiedDate').val() },
                            "AccountNumber": { "eq": $('#accountNumber').val() },
                        }
                    }
                }
            },
            "language": {
                "search": "",
                "searchPlaceholder": "Search..."
            },
           "columns": [
               { "data": "BusinessEntityID", searchable: false },
               { "data": "CreditRating", searchable: false },
               { "data": "ActiveFlag", "searchable": false },
               { "data": "AccountNumber", searchable: true },
               { "data": "ModifiedDate", "searchable": false},
            ],
           "columnDefs": [
               {
                   "render": function (data, type, row) {
                       date = new Date(parseInt(row.ModifiedDate.replace("/Date(", "").replace(")/", ""), 10));

                       return date.toLocaleDateString();
                   },
                   "targets": 4
               }
           ]

        });

        $('.reload-table').on('change', function () {
            table.ajax.reload();
        });
    </script>
}