src/Tests/integrationtests/Tests.Integration.Mvc/Controllers/HomeController.cs
namespace Tests.Integration.Mvc.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net.Http;
    using System.Web.Mvc;
    using JQDT.MVC;
    using TestData.Models;

    public class HomeController : Controller
    {
        public static IQueryable<AllTypesModel> Data { get; set; }

        public ActionResult Index()
        {
            return this.View();
        }

        public ActionResult AllTypesData(bool paging = true, bool searching = true, bool showString = true, bool showChar = true)
        {
            this.ViewBag.Paging = paging.ToString().ToLower();
            this.ViewBag.Searching = searching.ToString().ToLower();
            this.ViewBag.ShowString = showString.ToString().ToLower();
            this.ViewBag.ShowChar = showChar.ToString().ToLower();
            this.ViewBag.dataSourceApp = Configuration.SettingsProvider.Get("dataSourceApp");
            this.ViewBag.WebApi2Url = Configuration.SettingsProvider.Get("webApi2Url");

            return View();
        }

        [JQDataTable]
        public ActionResult GetData()
        {
            return this.View(Data);
        }

        public ActionResult GetFullData()
        {
            var dataSourceApp = Configuration.SettingsProvider.Get("dataSourceApp");
            if (dataSourceApp == "mvc")
            {
                return this.Json(Data, JsonRequestBehavior.AllowGet);
            }
            else if (dataSourceApp == "webapi2")
            {
                var http = new HttpClient();
                var url = Configuration.SettingsProvider.Get("webApi2Url") + "/home";
                var result = http.GetAsync(url).Result;
                var jsonString = result.Content.ReadAsStringAsync().Result;
                var json = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<AllTypesModel>>(jsonString);
                Console.WriteLine(jsonString);

                return this.Json(json, JsonRequestBehavior.AllowGet);
            }
            else
            {
                throw new ArgumentException("Invalid data source app " + dataSourceApp);
            }
        }
    }
}

src/Tests/integrationtests/Tests.Integration.Mvc/Controllers/TestOnActionExecutedController.cs
namespace Tests.Integration.Mvc.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;
    using JQDT.Models;

    public class TestOnActionExecutedController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [CustomOnActionExecuted]
        public ActionResult GetData()
        {
            var data = new List<OnActionExecutedTestModel>();
            for (int i = 1; i <= 5; i++)
            {
                data.Add(new OnActionExecutedTestModel { Number = i });
            }

            return this.View(data.AsQueryable());
        }
    }

    public class OnActionExecutedTestModel
    {
        public int Number { get; set; }
    }

    public class CustomOnActionExecutedAttribute : JQDT.MVC.JQDataTableAttribute
    {
        public override void OnDataProcessed(ref object data, RequestInfoModel requestInfoModel)
        {
            var list = ((IQueryable<OnActionExecutedTestModel>)data).ToList();
            for (int i = 6; i <= 10; i++)
            {
                list.Add(new OnActionExecutedTestModel { Number = i });
            }

            data = list.AsQueryable();
        }
    }
}

src/Tests/integrationtests/Tests.Integration.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="@Tests.Integration.Mvc.Configuration.SettingsProvider.Get("jQueryDataTablesCssCdn")" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("All Types Data", "AllTypesData", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Tests.Integration.Mvc.Configuration.SettingsProvider.Get("jQueryDataTablesJsCdn")"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

src/Tests/integrationtests/Tests.Integration.Mvc/Views/TestOnActionExecuted/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Test</th>
        </tr>
    </thead>

    <tfoot>
        <tr>
            <th>Test</th>
        </tr>
    </tfoot>
</table>

@section Scripts {
    <script>
        var table = $('table').DataTable({
            "proccessing": true,
            "serverSide": true,
            "ajax": {
                @if (ViewBag.dataSourceApp == "mvc")
                {
                @:url: "@Url.Action("GetData", "TestOnActionExecuted")",
                } else if (ViewBag.dataSourceApp == "webapi2")
                {
                @:url: "@ViewBag.WebApi2Url/OnActionExecutedTest",
                }
                type: 'POST',
            },
           "columns": [
               { "data": "Number" },
            ]
        });
    </script>
}